{% set version = "5.0.1" %}

package:
  name: tango-idl
  version: "{{ version }}"

source:
  git_rev: {{ version }}
  git_url: https://gitlab.com/tango-controls/tango-idl.git
requirements:
  build:
    - {{ compiler('cxx') }}

about:
  home: http://www.tango-controls.org
  license: LGPL3
#  license_file: COPYING
  summary: A software toolkit for building control systems
