{% set version = "9.4.0" %}

package:
  name: cpptango
  version: "9.4.0"

source:
  git_url: https://github.com/tango-controls/cppTango.git
  git_rev: tango-9-lts

build:
  number: 0
  string: alpha
  run_exports :
    - {{ pin_subpackage('cpptango', min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - libtool
    - {{ compiler('cxx') }}
    - cmake
  host:
    - omniorb
    - cppzmq
    - tango-idl
  run:
    - {{ pin_compatible('omniorb', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('zeromq', min_pin='x.x', max_pin='x.x') }}

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Tango-Controls C++ library'
  description: |
   This is the Tango-Controls C++ library (a.k.a. cppTango). 
   Tango-Controls is a software toolkit for building control systems.
  dev_url: https://github.com/tango-controls/cppTango
  doc_url: https://tango-controls.github.io/cppTango-docs
  doc_source_url: https://github.com/tango-controls/cppTango-docs
